from rtkit.resource import RTResource
from rtkit.authenticators import CookieAuthenticator

from rtkit.errors import RTResourceError
from rtkit import set_logging
import logging

set_logging('debug')
logger = logging.getLogger('rtkit')
response = ''

host = 'domo-kun.noip.me/rt/'
usr = 'twoskie@uc.pt'
pwd = 'shutup'
resource = RTResource('http://'+host+'/REST/1.0/', usr, pwd, CookieAuthenticator)

content = {'content': {
            'Queue': 'general',
            'Requestor': 'twoskie@uc.pt',
            'Subject': 'Pytest Creation Test',
            'Cc': '',
            'AdminCc': '',
            'Owner': 'nobody',
            'Status': 'new',
            'Priority': '25',
            'InitialPriority': '25',
            'FinalPriority': '',
            'TimeEstimated': '',
            'Starts': '',
            'Due': '',
            'Text': 'Hey! This is a ticket generated by running the test_rtkit_creation',
            'cf.{is - informatica e sistemas}': 'dir', }
        }

try:
    response = resource.post(path='ticket/new', payload=content)
    logger.info(response.parsed)
except RTResourceError as e:
    logger.error(e.response.status_int)
    logger.error(e.response.status)
    logger.error(e.response.parsed)

assert response.status_int != 400
assert response.status_int == 200
